#!/usr/bin/python3
from math import *

class Param:
    def __init__(self, x0, y0, z0, x1, y1, z1, n):
        self.x0 = x0
        self.y0 = y0
        self.z0 = z0
        self.x1 = x1
        self.y1 = y1
        self.z1 = z1
        self.n = n

def vector(our_param):
    # Vitesse instantanée = position initiale - position instantanée
    vx = our_param.x1 - our_param.x0
    vy = our_param.y1 - our_param.y0
    vz = our_param.z1 - our_param.z0
    print(f"The velocity vector of the ball is:")
    print(f"({vx:.2f}, {vy:.2f}, {vz:.2f})")

    # Position au cours du temps = position finale * t + position finale
    xt = (vx * our_param.n) + our_param.x1
    yt = (vy * our_param.n) + our_param.y1
    zt = (vz * our_param.n) + our_param.z1
    print(f"At time t + {our_param.n}, ball coordinates will be:")
    print(f"({xt:.2f}, {yt:.2f}, {zt:.2f})")

    # Calcul de l'angle
    velocity   = sqrt(pow(vx, 2) + pow(vy, 2) + pow(vz, 2))
    if velocity == 0:
        incid_angle = 0
    else:
        incid_angle = abs(90 - degrees(acos(vz / velocity)))
    if (z1 >= 0 and vz < 0) or (z1 < 0 and vz >= 0):
        print("The incidence angle is:")
        print("%.2f" % incid_angle, "degrees")
    if (incid_angle == 0 and zt == 0):
        print("The incidence angle is:")
        print("%.2f" % incid_angle, "degrees")
    else:
        print("The ball won't reach the paddle.")
    exit (0)

if __name__ == "__main__":
    import sys
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"): 
        print("USAGE")
        print("    ./101pong x0 y0 z0 x1 y1 z1 n")
        print()
        print("DESCRIPTION")
        print("    x0  ball abscissa at time t - 1")
        print("    y0  ball ordinate at time t - 1")
        print("    z0  ball altitude at time t - 1")
        print("    x1  ball abscissa at time t")
        print("    y1  ball ordinate at time t")
        print("    z1  ball altitude at time t")
        print("    n   time shift (greater than or equal to zero, integer)")
        sys.exit(0)
    if  (len(sys.argv) != 8):
        sys.exit(84)

    try:
        x0 = float(sys.argv[1])
        y0 = float(sys.argv[2])
        z0 = float(sys.argv[3])
        x1 = float(sys.argv[4])
        y1 = float(sys.argv[5])
        z1 = float(sys.argv[6])
        n = int(sys.argv[7])
    except ValueError:
        sys.exit(84)
    our_param = Param(float(sys.argv[1]), float(sys.argv[2]), float(sys.argv[3]), float(sys.argv[4]), float(sys.argv[5]), float(sys.argv[6]), int(sys.argv[7]))
    if n < 0:
        sys.exit(84)
    vector(our_param)
