version: '3'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/configuration.yml
    env_file:
      - .env

volumes:
  jenkins_home:
